create_boot_directory

if {![have_spec x86_64] && ![have_spec arm_v7] ||
	[expr [have_spec sel4] && ![have_spec x86_64]]} {
	puts "Java is not supported on this platform. Valid platforms are x86_64 and arm_v7a."
	exit 0
}

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/terminal \
                  [depot_user]/src/init \
                  [depot_user]/src/posix \
                  [depot_user]/src/ncurses \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_pipe \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/fs_rom\
                  [depot_user]/pkg/jdk 
                  

# write default vimrc file
set vimrc_fd [open [run_dir]/genode/vimrc w]
puts $vimrc_fd {
set noloadplugins
set hls
set nocompatible
set laststatus=2
set noswapfile
set viminfo=}
close $vimrc_fd

install_config {


<config verbose="yes">
	
	<parent-provides>
		<service name="ROM"/>
		<service name="LOG"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="PD"/>
		<service name="IRQ"/>
		<service name="IO_PORT"/>
		<service name="IO_MEM"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1500" managing_system="yes">
		<resource name="RAM" quantum="64M"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer">   <child name="timer"/> </service>
			<service name="Capture"> <child name="nitpicker"/> </service>
			<service name="Event">   <child name="nitpicker"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides>
			<service name="Gui"/> <service name="Capture"/> <service name="Event"/>
		</provides>
		<config focus="rom">
			<capture/> <event/>
			<domain name="default" layer="2" content="client" label="no" hover="always"/>
			<default-policy domain="default"/>
		</config>
		<route>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="terminal" caps="110">
		<resource name="RAM" quantum="6M"/>
		<provides><service name="Terminal"/></provides>
		<route>
			<service name="ROM" label="config"> <parent label="terminal.config"/> </service>
			<service name="Gui"> <child name="nitpicker"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

<!--
	<start name="test-terminal_echo">
			<resource name="RAM" quantum="1M"/>
	</start>	

	<start name="vfs" caps="120">
		<resource name="RAM" quantum="30M"/>
		<provides><service name="File_system"/></provides>
		<config>
			<vfs>
				<tar name="coreutils.tar" />
				<tar name="vim.tar" />
				<tar name="bash.tar" />

				<dir name="home"> <ram/> </dir>
				<dir name="share"> <dir name="vim"> <rom name="vimrc"/> </dir> </dir>
				<dir name="tmp"> <ram/> </dir>
				<dir name="dev">
					<zero/> <null/> <terminal/>
					<inline name="rtc">2018-01-01 00:01</inline>
				</dir>
				<dir name="pipe"> <pipe/> </dir>
			</vfs>

			<policy label_prefix="vfs_rom" root="/"/>
			<default-policy root="/" writeable="yes"/>
		</config>
	</start>

	<start name="vfs_rom">
		<resource name="RAM" quantum="30M"/>
		<binary name="fs_rom"/>
		<provides> <service name="ROM"/> </provides>
		<config/>
		<route>
			<service name="File_system"> <child name="vfs"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	-->
	<start name="java" caps="500">
		<resource name="RAM" quantum="96M" />
		<route>
			<service name="ROM" label="zip.lib.so">
				<parent label="jzip.lib.so" />
			</service>
			<service name="ROM" label="net.lib.so">
				<parent label="jnet.lib.so" />
			</service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
		<config ld_verbose="yes">
			<arg value="/bin/java" />
			<arg value="-XX:+NeverActAsServerClassMachine"/>
			<arg value="-XX:+UnlockDiagnosticVMOptions"/>
			<arg value="-XX:-ImplicitNullChecks"/>
			<arg value="-XX:+CITime" />
			<!-- <arg value="-Xcomp"/> -->
			<!-- <arg value="-XX:+PrintCompilation" /> -->
			<arg value="-jar" />
			<arg value="hello.jar" />
			<!--<libc stdin="/dev/log" stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" /> -->
			<libc stdin="/dev/terminal" stdout="/dev/terminal" stderr="/dev/terminal" rtc="/dev/rtc" />
			<vfs rtc="/dev/rtc">
				<dir name="dev">
					<log/><null/><inline name="rtc">2000-01-01 00:00</inline>
					<terminal label="terminal"/>
				</dir>
				<dir name="bin">
					<rom name="java" />
				</dir>
				<dir name="lib">
					<rom name="java.lib.so" />
					<inline name="jvm.cfg">-server KNOWN -client IGNORE </inline>
					<dir name="server">
						<rom name="jvm.lib.so" />
					</dir>
				</dir>
				<dir name="modules">
					<tar name="classes.tar" />
				</dir>
				<tar name="hello_arm.tar" />
				<tar name="hello.tar" />
				<rom name="zip.lib.so" />
				<rom name="nio.lib.so" />
				<rom name="net.lib.so" />

					<rom label="classes.tar"/>
					<rom label="hello.tar"/>
					<rom label="java"/>
					<rom label="java.lib.so"/>
					<rom label="jimage.lib.so"/>
					<rom label="jli.lib.so"/>
					<rom label="jnet.lib.so"/>
					<rom label="jvm.lib.so"/>
					<rom label="jzip.lib.so"/>
					<rom label="libc.lib.so"/>
					<rom label="libm.lib.so"/>
					<rom label="vfs_pipe.lib.so"/>
					<rom label="ld.lib.so"/>
					<rom label="management.lib.so"/>
					<rom label="nio.lib.so"/>
					<rom label="stdcxx.lib.so"/>
					<rom label="vfs.lib.so"/>
					<rom label="tzdb.dat"/>
					<rom label="zlib.lib.so"/>
				

			</vfs>
			<env key="TERM" value="screen"/>
			<env key="PATH" value="/bin" />
		</config>
	</start>
	
</config>}

set fd [open [run_dir]/genode/focus w]
puts $fd "<focus label=\"terminal -> \" domain=\"default\"/>"
close $fd

#build { lib/ld test/fork test/execve server/terminal test/terminal_echo}
build { lib/ld test/fork test/execve }

#build_boot_image { ld.lib.so libc.lib.so libm.lib.so vfs.lib.so posix.lib.so terminal test-terminal_echo }
build_boot_image { ld.lib.so libc.lib.so libm.lib.so vfs.lib.so posix.lib.so terminal }

run_genode_until "child \"java\" exited with exit value 0" 200
 